/*
 * w.java
 *
 * Created on __DATE__, __TIME__
 */
package form;

import java.awt.Toolkit;

/**
 *
 * @author  __USER__
 */
public class Waiting extends javax.swing.JDialog {
	public Waiting(java.awt.Frame parent, boolean modal) {

		/** Creates new form w */
		super(parent, modal);
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		this.setTitle("正在解析中");
		this.setLocation(480, 300);
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setIconImage(null);

		jLabel1.setFont(new java.awt.Font("楷体_GB2312", 0, 18));
		jLabel1
				.setText("正在解析当中请等待...");

		jLabel2
				.setIcon(new javax.swing.ImageIcon(
						getClass()
								.getResource(
										"/load1/20100926_ajax-loading_28e5abef-3bf3-48e8-a6fd-94dee7d65511.gif"))); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(86,
						Short.MAX_VALUE).addComponent(jLabel2,
						javax.swing.GroupLayout.PREFERRED_SIZE, 34,
						javax.swing.GroupLayout.PREFERRED_SIZE).addGap(18, 18,
						18).addComponent(jLabel1,
						javax.swing.GroupLayout.PREFERRED_SIZE, 197,
						javax.swing.GroupLayout.PREFERRED_SIZE).addGap(60, 60,
						60)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				50,
																				50,
																				50)
																		.addComponent(
																				jLabel2))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				32,
																				32,
																				32)
																		.addComponent(
																				jLabel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				62,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(39, Short.MAX_VALUE)));
		this.setIconImage(Toolkit.getDefaultToolkit().createImage(this.getClass().getResource("/load1/apple.JPG")));
		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				final Waiting dialog = new Waiting(new javax.swing.JFrame(), true);
//				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//					public void windowClosing(java.awt.event.WindowEvent e) {
//						System.exit(0);
//					}
//				});
				new Thread(){
					@Override
					public void run() {
						// TODO Auto-generated method stub
						super.run();
						for (int i = 0; i < 888888; i++) {
							System.out.println(i);
//							if(i==444444){
//								dialog.dispose();
//							}
						}
						dialog.dispose();
					};
				}.start();
				dialog.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	// End of variables declaration//GEN-END:variables

}