/*
 * f.java
 *
 * Created on __DATE__, __TIME__
 */

package form;

import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.List;
import java.util.Properties;
import java.util.Vector;

import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.border.Border;

import com.sunmap.shpdata.tools.main.ImportData;

/**
 *
 * @author  __USER__
 */
public class f extends javax.swing.JFrame {

	/** Creates new form f */
	public f() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBorder(javax.swing.BorderFactory
				.createTitledBorder("\u6587\u4ef6"));

		jButton1.setText("load files");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addGap(22, 22, 22)
										.addComponent(
												jTextField1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												230, Short.MAX_VALUE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jButton1).addGap(10, 10,
												10)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																33,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButton1))
										.addContainerGap(20, Short.MAX_VALUE)));

		jPanel2.setBorder(javax.swing.BorderFactory
				.createTitledBorder("\u65e5\u5fd7"));

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jButton2.setText("OK");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("Cannel");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(18, 18, 18)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				70,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButton3))
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																281,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(65, Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel2Layout
										.createSequentialGroup()
										.addGap(19, 19, 19)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												153, Short.MAX_VALUE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton2)
														.addComponent(jButton3))
										.addContainerGap()));

		jPanel3
				.setBorder(javax.swing.BorderFactory
						.createTitledBorder("\u5df2\u5bfc\u5165\u7684\u6587\u4ef6\u4e2a\u6570/\u603b\u6570"));

		jLabel1.setText("0");

		jLabel2.setText("/");

		jLabel3.setText("0");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(18, 18, 18)
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jLabel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												12,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel3).addContainerGap(
												306, Short.MAX_VALUE)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel3Layout.createSequentialGroup().addGroup(
						jPanel3Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										32, Short.MAX_VALUE).addComponent(
										jLabel2).addComponent(jLabel3))
						.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jPanel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap(
																				53,
																				Short.MAX_VALUE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jPanel3,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								jPanel2,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE))
																		.addGap(
																				38,
																				38,
																				38)))));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(25, 25, 25).addComponent(
						jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE).addGap(16, 16,
						16).addComponent(jPanel3,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE).addGap(18, 18,
						18).addComponent(jPanel2,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(27, Short.MAX_VALUE)));
		this.setIconImage(Toolkit.getDefaultToolkit().createImage(this.getClass().getResource("/load1/apple.JPG")));
		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTextField1.getText() != null) {
			strPath = null;
			jTextField1.setText(null);
			JOptionPane jop = new JOptionPane();
			jop.showMessageDialog(this, "清除成功");
		} else {
			JOptionPane jop = new JOptionPane();
			jop.showMessageDialog(this, "清除失败");
		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {

		Properties pro = new Properties();
		try {
			File file = new File(this.getClass().getClassLoader().getResource("conf.properties").toURI());
//			File file = new File("conf.properties");
			FileInputStream in = new FileInputStream(file);
			pro.load(in);
			in.close();
			if(jTextField1 != null){
				FileOutputStream out = new FileOutputStream(file);
				pro.setProperty("inputPath", jTextField1.getText());
				pro.store(out, null);
				if(ImportData.x == 0){
					return;
				}
				jTextArea1.setText("");
				 t = new Thread(){
					public void run() {
						super.run();
						try {
							String path1 = new File(this.getClass().getProtectionDomain().getCodeSource().getLocation().getFile()).getParentFile().getParent();
//							System.out.println(path1 + "as.bat");
//							doWaitFor(Runtime.getRuntime().exec("cmd /c "  + "E:\\ss\\run.bat"));
							new ImportData().main(new String[]{});
//							System.out.println("sdsddddddddddd");
//							readFile();
						} catch (Exception e) {
							ImportData.x =1;
							e.printStackTrace();
						}
					};
				};
				t.start();
				out.close();
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		JFileChooser f = new JFileChooser("");
		f.setFileSelectionMode(f.DIRECTORIES_ONLY);
		int i = f.showOpenDialog(f.this);
		if (i == f.APPROVE_OPTION) {
			File file = f.getSelectedFile();
			strPath = file.getPath();
			jTextField1.setText(strPath);
		}
		System.out.println(strPath);
	}

	public void readFile(){
		try {
			
			InputStream is = this.getClass().getClassLoader().getResourceAsStream("log.txt");
			InputStreamReader isr = new InputStreamReader(is);
			BufferedReader in = new BufferedReader(isr);
//			fss.createNewFile();
//			System.out.println(fss.exists());
//			System.out.println(fss.getPath());
			String str1 = "";
//			while(true) {
//				while((str1 = in.readLine()) != null){
					System.out.println(str1);
					jTextArea1.append(str1 + "\r");
					jTextArea1.paintImmediately(
							jTextArea1.getBounds());
					jTextArea1.setCaretPosition(jTextArea1.getText().length()-1);
//				}
//			}
		} catch (Exception e) {
			System.out.println("文件不存在");
			e.printStackTrace();
		}
	}
	
	public int doWaitFor(Process p) {
		int exitValue = -1; // returned to caller when p is finished
		byte[] t = new byte[1024];
		try {

			InputStream in = p.getInputStream();
			InputStream err = p.getErrorStream();
			boolean finished = false; // Set to true when p is finished
			while (!finished) {
				try {
					while (in.available() > 0) {
						int length = in.read(t, 0, 1024);
						System.out.print(new String(t, 0, length));
						jTextArea1.append(new String(t, 0, length));
						jTextArea1.paintImmediately(
								jTextArea1.getBounds());
						jTextArea1.setCaretPosition(jTextArea1.getText().length()-1);
					}
					while (err.available() > 0) {
						int length = err.read(t, 0, 1024);
						System.out.print(new String(t, 0, length));
						jTextArea1.append(new String(t, 0, length));
						jTextArea1.paintImmediately(jTextArea1.getBounds());
						jTextArea1.setCaretPosition(jTextArea1.getText().length()-1);
					}
					exitValue = p.exitValue();
					finished = true;
				} catch (IllegalThreadStateException e) {
					Thread.currentThread().sleep(100);
				}
			}

		} catch (Exception e) {
			System.err.println("doWaitFor(): unexpected exception - ");
			e.printStackTrace();
		}
		return exitValue;
	}
	
	static JPanel showBorder(Border b){
		JPanel jp = new JPanel();
		jp.setLayout(new BorderLayout());
		String nm = b.getClass().toString();
		nm = nm.substring(nm.lastIndexOf('.') + 1);
		jp.add(new JLabel(nm, JLabel.CENTER), BorderLayout.CENTER);
		jp.setBorder(b);
		return jp;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		try {
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		} catch (Exception e) {
			e.printStackTrace();
		}
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new f().setVisible(true);
			}
		});

	}

	
	public static void setTextCon(String ss){
		jTextArea1.append(ss + "\n");
		jTextArea1.paintImmediately(
				jTextArea1.getBounds());
		jTextArea1.setCaretPosition(jTextArea1.getText().length()-1);
	}
	
	public static void setLabel1(String ds){
		jLabel1.repaint();
		jLabel1.setText(ds);
	}
	public static void setLabel3(String ds){
		jLabel3.repaint();
		jLabel3.setText(ds);
	}
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private static javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private static javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private  static javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField1;
	
	// End of variables declaration//GEN-END:variables
	private String strPath;
	private List<String> list = new Vector<String>();
	private String[] strPath1 = new String[] {};
	private Thread t;
}